name: Setup and cache

description: Setup for node and pnpm

inputs:
  node-version:
    required: false
    description: Node version for setup-node
    default: 20.x

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - name: Set node version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
